### ISSUE TITLE
No module named 'gntk_cond'

### ISSUE THREAD

**Issue by hualiu829** [NUS-HPC-AI-Lab/GEOM#1]
Hello, when I was running your code `python condense_transduct_2.py`, I encountered an error message saying 'No module named 'gntk_cond''. Could you please upload the 'gntk_cond.py' file?

**Comment by Raf-Chen** [comment]
Thanks for your attention, gntk_cond is not needed in our method, you can directly comment out the code that imports gntk_cond. We also update the repo now.

**Comment by hualiu829** [comment]
Thanks for your reply! Got it.

Hua

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Yuchen Zhang ***@***.***>
发送时间: Monday, June 24, 2024 2:36:15 AM
收件人: NUS-HPC-AI-Lab/GEOM ***@***.***>
抄送: Liu, Hua ***@***.***>; Author ***@***.***>
主题: Re: [NUS-HPC-AI-Lab/GEOM] No module named 'gntk_cond' (Issue #1)


Closed #1<https://urldefense.com/v3/__https://github.com/NUS-HPC-AI-Lab/GEOM/issues/1__;!!HXCxUKc!2rBrKVwLfFpPIbnHLcJD5ZpGDx0w2ni7IA50JbPjIdo4X4znlRlXMDwQAblwHTg6_CZZvxiFTTt0jNaHVMU_ggec$> as completed.

―
